site_name: CORIOLIX Docs
nav:
    - Home: index.md
    - How to Access CORIOLIX: access.md
    - CORIOLIX Pages:
        - Cruise Charts: charts.md
        - Sensor Plots: plots.md
        - Status: status.md
        - Sensors: sensors.md
        - Data: data.md
        - Documents: documents.md
        - Cruises: cruises.md
        - User Account: account.md
    - CORIOLIX Deployments:
        - Oceanus_Deployment: oceanus_deploy.md
        - Endeavor Deployment: endeavor_deploy.md
theme: readthedocs
