site_name: CORIOLIX Docs
nav:
    - Home: index.md
    - Getting Started:
        - How to access CORIOLIX: HT_access.md
        - How to create an account: HT_account.md
    - CORIOLIX Pages:
        - Cruise Charts: charts.md
        - Sensor Plots: plots.md
        - Status: status.md
        - Sensors: sensors.md
        - Data: data.md
        - Documents: documents.md
        - Cruises: cruises.md
        - My Account: account.md
    - CORIOLIX Deployments:
        - R/V Oceanus: oceanus_deploy.md
        - R/V Endeavor: endeavor_deploy.md
        - R/V Point Sur: ptsur_deploy.md
theme: readthedocs
