site_name: CORIOLIX Docs
site_url: http://127.0.0.1:8000
nav:
  - Home: index.md
  - Getting Started:
      - How to access CORIOLIX: HT_access.md
      - How to create an account: HT_account.md
      - How to access underway data: HT_data_access.md
      - How to onboard sensors: HT_sensor_onboard.md
  - User Interface Pages:
      - Cruise Tools: PAGES_tools.md
      - Cruise Chart: PAGES_charts.md
      - Sensor Plots: PAGES_plots.md
      - Status: PAGES_status.md
      - Sensors: PAGES_sensors.md
      - Data: PAGES_data.md
      - Documents: PAGES_documents.md
      - Settings: PAGES_settings.md
      - My Account: PAGES_account.md
  - APIs:
      - Use Cases: API_use_cases.md
      - Data Model: API_model.md
      - API endpoints: API_endpoints.md
  - ADMINISTRATION:
      - Installation: INSTALL_coriolix.md
      - Upgrade: UPGRADE_coriolix.md
      - Logs: LOGS_coriolix.md
theme: readthedocs
